import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tm': {
          'noConnection1': 'Aragatnaşyk ýok',
          'noConnection2': 'Internede baglanyp bolmady.Internet sazlamalaryňyzy barlap gaýtadan synanşyň !',
          'noConnection3': 'Täzeden synanyş',
          'home': 'Baş sahypa',
          'category': 'Kategoriýa',
          'favorites': 'Halanlarym',
          'user': 'Ulanyjy',
          'me': 'Men',
          'Recommended': 'Maslahat berilenler',
          'tellafriend': 'Dostlaryň bilen paýlaş',
          'feedback': 'Teswir ýazmak',
          'aboutapp': 'Biz barada',
          'ClearCaches': 'Keşini arassalamak',
          'NightMode': 'Garaňky tema',
          'Language': 'Dil',
          'SelectLanguage': 'Dil saýlaň',
          'English': 'Iňlis dili',
          'Russian': 'Rus dili',
          'Turkmen': 'Türkmen dili',
          'Download': 'Ýüklemek',
          'SetWallpaper': 'Diwar kagyzy belle',
          'Share': 'Paýlaşmak',
          'Setas': 'Diwar kagyz belle',
          'HomeScreen': 'Baş ekran',
          'LockScreen': 'Gulply ekran',
          'Both': 'Gulp we Öý ekranlary',
          'Oboi': 'Diwar kagyzy bellenildi',
          'Cat': 'Pişik',
          'Baby': 'Çaga',
          'Gold Fish': 'Balyk',
          'Travel': 'Syýahat',
          'Mountain': 'Dag',
          'Beach': 'Deňiz kenary',
          'Forest': 'Tokaý',
          'Sky': 'Asman',
          'Birds': 'Guşlar',
          'Dog': 'Itler',
          'Horse': 'Atlar',
          'Vacation': 'Dynç alyşlar',
          'Lion': 'Bars',
          'Rose': 'Bägül',
          'Garden': 'Bag',
          'Fruit': 'Miweler',
          'Coffee': 'Kofýa',
          'Couple': 'Jübüt',
          'Dark': 'Garaňky',
          'Animals': 'Haýwanlar',
          'Cat': 'Pişik',
          'Flowers': 'Güller',
          'Nature': 'Tebigat',
          'Art': 'Şekillendiriş',
          'Space': 'Älem',
          'Love': 'Söýgi',
          'yellow': 'Sary',
          'green': 'Ýaşyl',
          'blue': 'Gök',
          'orange': 'Mämişi',
          'pink': 'Gülgüne',
          'black': 'Gara',
          'brown': 'Goňur',
          'nolikefound': 'Entek Siziň halan diwar kagyzlaryňyz ýok.',
          'remove': 'Aýryldy',
          'added': 'Goşuldy',
        },
        'en': {
          'noConnection1': 'No connection',
          'noConnection2': 'Unable to connect to the Internet. Please check Internet and region!',
          'noConnection3': 'Try again',
          'home': 'Home',
          'category': 'Сategory',
          'favorites': 'Favorites',
          'user': 'User',
          'me': 'Me',
          'Recommended': 'Recommended',
          'tellafriend': 'Tell a Friend',
          'feedback': 'Feedback',
          'aboutapp': 'About Us',
          'ClearCaches': 'Clear Cache',
          'NightMode': 'Dark mode',
          'Language': 'Language',
          'SelectLanguage': 'Select language',
          'English': 'English',
          'Russian': 'Russian',
          'Turkmen': 'Turkmen',
          'Download': 'Download',
          'SetWallpaper': 'Set Wallpaper',
          'Share': 'Share',
          'Setas': 'Set as',
          'HomeScreen': 'Home Screen',
          'LockScreen': 'Lock Screen',
          'Both': 'Home and Lock Screens',
          'Oboi': 'Wallpaper applied',
          'Cat': 'Cat',
          'Baby': 'Baby',
          'Gold Fish': 'Fish',
          'Travel': 'Travel',
          'Mountain': 'Mountain',
          'Beach': 'Beach',
          'Forest': 'Forest',
          'Sky': 'Sky',
          'Birds': 'Birds',
          'Dog': 'Dog',
          'Horse': 'Horse',
          'Vacation': 'Vacation',
          'Lion': 'Lion',
          'Rose': 'Rose',
          'Garden': 'Garden',
          'Fruit': 'Fruit',
          'Coffee': 'Coffee',
          'Couple': 'Couple',
          'Dark': 'Dark',
          'Animals': 'Animals',
          'Flowers': 'Flowers',
          'Nature': 'Nature',
          'Art': 'Art',
          'Space': 'Space',
          'Love': 'Love',
          'yellow': 'Yellow',
          'green': 'Green',
          'blue': 'Blue',
          'orange': 'Orange',
          'pink': 'Pink',
          'black': 'Black',
          'brown': 'Brown',
          'nolikefound': 'You have no favorite wallpapers yet.',
          'remove': 'Removed',
          'added': 'Added'
        },
        'ru': {
          'noConnection1': 'Нет связи',
          'noConnection2': 'Невозможно подключиться к Интернету. Пожалуйста проверьте настройки Интернета и повторите попытку!',
          'noConnection3': 'Попробуйте снова',
          'home': 'Главная',
          'category': 'Категория',
          'favorites': 'Избранное',
          'user': 'Пользователь',
          'me': 'Я',
          'Recommended': 'Рекомендуемые',
          'tellafriend': 'Расскажи другу',
          'feedback': 'Написать отзыв',
          'aboutapp': 'О нас',
          'ClearCaches': 'Очистить кеши',
          'NightMode': 'Темный режим',
          'Language': 'Язык',
          'SelectLanguage': 'Выберите язык',
          'English': 'Английский язык',
          'Russian': 'Русский язык',
          'Turkmen': 'Туркменский язык',
          'Download': 'Скачать',
          'SetWallpaper': 'Установить как обои',
          'Share': 'Поделиться',
          'Setas': 'Установить как обои',
          'HomeScreen': 'Главный экран',
          'LockScreen': 'Экран блокировки',
          'Both': 'Главный экран и экран блокировки',
          'Oboi': 'Oбои применены',
          'Cat': 'Кот',
          'Baby': 'Малыш',
          'Gold Fish': 'Рыбка',
          'Travel': 'Путешествие',
          'Mountain': 'Гора',
          'Beach': 'Пляж',
          'Forest': 'Лес',
          'Sky': 'Небо',
          'Birds': 'Птицы',
          'Dog': 'Собака',
          'Horse': 'Лошадь',
          'Vacation': 'Отпуск',
          'Lion': 'Лев',
          'Rose': 'Роза',
          'Garden': 'Сад',
          'Fruit': 'Фрукты',
          'Coffee': 'Кофе',
          'Couple': 'Пара',
          'Dark': 'Темный',
          'Animals': 'Животные',
          'Flowers': 'Цветы',
          'Nature': 'Природа',
          'Art': 'Искусство',
          'Space': 'Космос',
          'Love': 'Любовь',
          'yellow': 'Желтый',
          'green': 'Зеленый',
          'blue': 'Синий',
          'orange': 'Оранжевый ',
          'pink': 'Розовый',
          'black': 'Черный',
          'brown': 'Коричневый',
          'nolikefound': 'У вас еще нет избранных обоев ',
          'remove': 'Удалено',
          'added': 'Добавлен'
        }
      };
}
